name: GitGuardian Secret Scan

on: [push, pull_request]

jobs:
  ggshield-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: GitGuardian Scan
        uses: GitGuardian/gg-shield-action@v1
        env:
          GG_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
